name: RightClickHarvest4Spigot
version: '1.0'
main: codes.domino.rightclickharvest4spigot.RightClickHarvest4Spigot
api-version: '1.20'
authors: [ domino ]
description: A mod that automatically parkours to the next block.
website: https://domino.codes
